server:
  port: 8761
spring:
  application:
    name: eurekaserver
  config:
    import: "optional:configserver:http://localhost:8763/"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

info:
  app:
    name: "eureka-server"
    description: "MedSoft Eureka Server Application"
    version: "1.0.0"

endpoints:
  shutdown:
    enabled: true

logging:
  level:
    com:
      umitcoban:
        eurekaserver: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
